spring:
  application:
    name: UserService

  server:
    port: 8080

  flyway: baseline-on-migrate=true

  datasource:
    url: jdbc:h2:mem:h-basic;
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
          ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true


addressservice:
  base:
    url: http://localhost:8080/