spring:
  application:
    name: AuthService
    security:
      jwt:
        secret-key: secret
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days


  server:
    port: 8081

  addressservice:
    base:
      url: http://localhost:8081/
