spring:
  application:
    name: AuthService

server:
  port: 8080


security:
#  user:
#     name: admin
#     password: admin
  jwt:
      secret:
        access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w
        refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days

addressservice:
  base:
    url: http://localhost:8081

