spring:
  application:
    name: AuthService

    security:
      jwt:
        secret-key: secret
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days

  server:
    port: 8081

  flyway: baseline-on-migrate=true

  datasource:
    url: jdbc:h2:mem:h-basic;
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  addressservice:
    base:
      url: http://localhost:8081/
